import React, { useEffect, useState } from 'react';
import { api, stages, stageFa } from './content';
import { Arrow, Icon } from './components';
import { useSite } from './context';

export default function Admin(){
 const {fa,settings,setSettings}=useSite(); const [auth,setAuth]=useState(false),[checking,setChecking]=useState(true),[tab,setTab]=useState('quotes'),[quotes,setQuotes]=useState([]),[shipments,setShipments]=useState([]),[contacts,setContacts]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[selected,setSelected]=useState(null),[draft,setDraft]=useState(settings);
 useEffect(()=>{api('/admin/session').then(()=>setAuth(true)).catch(()=>{}).finally(()=>setChecking(false));},[]);
 const load=async()=>{try{const [q,s,c]=await Promise.all([api('/admin/quotes'),api('/admin/shipments'),api('/admin/contacts')]);setQuotes(q);setShipments(s);setContacts(c);}catch(err){if(err.status===401)setAuth(false);setError(err.message);}};
 useEffect(()=>{if(auth)load();},[auth]);
 useEffect(()=>setDraft(settings),[settings]);
 async function login(e){e.preventDefault();setError('');setBusy(true);try{await api('/admin/login',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});setAuth(true);}catch(err){setError(fa?'ورود ناموفق بود. نام کاربری و رمز را بررسی کنید یا کمی بعد تلاش کنید.':err.message);}finally{setBusy(false);}}
 async function logout(){setError('');try{await api('/admin/logout',{method:'POST'});setAuth(false);setQuotes([]);setShipments([]);setContacts([]);}catch(err){setError(err.message);}}
 async function action(task){setBusy(true);setError('');setNotice('');try{await task();setNotice(fa?'تغییرات ذخیره شد.':'Changes saved.');await load();}catch(err){if(err.status===401)setAuth(false);setError(err.message);}finally{setBusy(false);}}
 async function createShipment(e){e.preventDefault();const form=e.currentTarget;const data=Object.fromEntries(new FormData(form));await action(async()=>{await api('/admin/shipments',{method:'POST',body:JSON.stringify(data)});form.reset();});}
 const qStatus=s=>fa?({New:'جدید',Contacted:'تماس گرفته شد',Closed:'بسته شده'}[s]):s;
 if(checking)return <div className="section container">{fa?'در حال بررسی دسترسی…':'Checking access…'}</div>;
 if(!auth)return <section className="section container admin-login"><div className="panel"><span className="feature-icon"><Icon name="LockKeyhole" size={27}/></span><span className="eyebrow">{fa?'ورود امن':'SECURE SIGN-IN'}</span><h1>{fa?'پنل مدیریت':'Admin dashboard'}</h1><p>{fa?'این بخش فقط برای مدیران شرکت است. پرتال اختصاصی مشتریان هنوز فعال نیست.':'This area is for company administrators only. Individual customer accounts are not enabled yet.'}</p><form onSubmit={login}><label>{fa?'نام کاربری':'Username'}<input name="username" autoComplete="username" defaultValue="admin" required dir="ltr"/></label><label>{fa?'رمز عبور':'Password'}<input name="password" type="password" autoComplete="current-password" required dir="ltr" maxLength={256}/></label>{error&&<p className="error" role="alert">{error}</p>}<button className="button" disabled={busy}>{busy?(fa?'در حال ورود…':'Signing in…'):(fa?'ورود به مدیریت':'Sign in')}<Arrow/></button></form><p className="sample-note">{fa?'برای ورود، مقدار ADMIN_PASSWORD را در بخش Secrets با رمز امن خود جایگزین کنید.':'To sign in, replace ADMIN_PASSWORD in Secrets with your own strong password.'}</p></div></section>;
 return <section className="section container admin-page"><div className="admin-heading"><div><span className="eyebrow">{fa?'مدیریت حمل‌ونقل':'OPERATIONS WORKSPACE'}</span><h1>{fa?'پنل مدیریت':'Admin dashboard'}</h1></div><button className="button outline" onClick={logout}><Icon name="LogOut" size={18}/>{fa?'خروج':'Sign out'}</button></div><div className="admin-tabs">{[['quotes','درخواست‌ها','Quotes','FileText',quotes.length],['shipments','محموله‌ها','Shipments','Truck',shipments.length],['contacts','پیام‌ها','Messages','Mail',contacts.length],['settings','اطلاعات شرکت','Company settings','Settings',null]].map(([id,f,e,icon,count])=><button key={id} className={tab===id?'active':''} onClick={()=>{setTab(id);setNotice('');setError('');}}><Icon name={icon} size={18}/>{fa?f:e}{count!==null&&<span>{count}</span>}</button>)}</div>{error&&<p className="error" role="alert">{error}</p>}{notice&&<p className="notice" role="status">{notice}</p>}
 {tab==='quotes'&&<div className="panel"><h2>{fa?'درخواست‌های استعلام قیمت':'Quote requests'}</h2>{!quotes.length?<p className="empty-state">{fa?'هنوز درخواستی ثبت نشده است.':'No quote requests yet.'}</p>:<div className="table-scroll"><table><thead><tr>{[fa?'شماره':'ID',fa?'نام / شرکت':'Name / company',fa?'مسیر':'Route',fa?'تاریخ':'Date',fa?'وضعیت':'Status',fa?'جزئیات':'Details'].map(s=><th key={s}>{s}</th>)}</tr></thead><tbody>{quotes.map(q=><React.Fragment key={q.id}><tr><td>#{q.id}</td><td><b>{q.data.name}</b><small>{q.data.company}</small></td><td>{q.data.origin} → {q.data.destination}</td><td>{new Date(q.createdAt).toLocaleDateString(fa?'fa-IR':'en-GB')}</td><td><select aria-label={(fa?'وضعیت درخواست ':'Quote status ')+q.id} value={q.status} disabled={busy} onChange={e=>action(()=>api('/admin/quotes/'+q.id,{method:'PATCH',body:JSON.stringify({status:e.target.value})}))}>{['New','Contacted','Closed'].map(s=><option key={s} value={s}>{qStatus(s)}</option>)}</select></td><td><button className="icon-button" aria-label={fa?'نمایش جزئیات':'View details'} onClick={()=>setSelected(selected===q.id?null:q.id)}><Icon name={selected===q.id?'ChevronUp':'ChevronDown'}/></button></td></tr>{selected===q.id&&<tr><td colSpan="6"><div className="quote-details">{Object.entries(q.data).map(([k,v])=><div key={k}><b>{fa?({name:'نام',company:'شرکت',phone:'تلفن',email:'ایمیل',service:'خدمت',origin:'مبدأ',destination:'مقصد',cargo:'کالا',weight:'وزن (کیلوگرم)',truck:'کامیون',pickup:'بارگیری',notes:'توضیحات'}[k]):k}</b><span>{v||'—'}</span></div>)}</div></td></tr>}</React.Fragment>)}</tbody></table></div>}</div>}
 {tab==='shipments'&&<><div className="panel"><h2>{fa?'ایجاد محموله جدید':'Create a shipment'}</h2><form className="form-grid shipment-form" onSubmit={createShipment}><label>{fa?'کد رهگیری یکتا':'Unique tracking code'}<input name="code" required pattern="[A-Za-z0-9-]{6,64}" maxLength={64} placeholder="IR-2026-001" dir="ltr"/></label><label>{fa?'مبدأ':'Origin'}<input name="origin" required maxLength={200}/></label><label>{fa?'مقصد':'Destination'}<input name="destination" required maxLength={200}/></label><label>{fa?'وضعیت':'Status'}<select name="status">{stages.map(s=><option value={s} key={s}>{fa?stageFa[s]:s}</option>)}</select></label><button className="button" disabled={busy}>{fa?'ثبت محموله':'Create shipment'}<Icon name="Plus" size={18}/></button></form></div><div className="panel"><h2>{fa?'محموله‌های ثبت‌شده':'Registered shipments'}</h2>{!shipments.length?<p className="empty-state">{fa?'هنوز محموله‌ای ایجاد نشده است.':'No shipments have been created.'}</p>:shipments.map(s=><ShipmentEditor key={s.id} shipment={s} busy={busy} save={data=>action(()=>api('/admin/shipments/'+s.id,{method:'PATCH',body:JSON.stringify(data)}))}/>)}</div></>}
 {tab==='contacts'&&<div className="panel"><h2>{fa?'پیام‌های دریافتی':'Contact messages'}</h2>{!contacts.length?<p className="empty-state">{fa?'هنوز پیامی دریافت نشده است.':'No messages yet.'}</p>:contacts.map(c=><article className="message-card" key={c.id}><h3>{c.name}</h3><a href={'mailto:'+c.email}>{c.email}</a><small>{new Date(c.createdAt).toLocaleString(fa?'fa-IR':'en-GB')}</small><p>{c.message}</p></article>)}</div>}
 {tab==='settings'&&<div className="panel"><h2>{fa?'نام و اطلاعات واقعی شرکت':'Your company details'}</h2><p className="muted">{fa?'این اطلاعات در سربرگ، پاورقی و صفحه تماس نمایش داده می‌شود.':'These details appear in the header, footer, and contact page.'}</p><form className="form-grid" onSubmit={e=>{e.preventDefault();action(async()=>setSettings(await api('/admin/settings',{method:'PUT',body:JSON.stringify(draft)})));}}>{[['brandFa','نام فارسی برند','Persian brand name'],['brandEn','نام انگلیسی برند','English brand name'],['phone','شماره تلفن با کد کشور','Phone with country code'],['email','ایمیل شرکت','Company email'],['address','آدرس دفتر (برای نقشه)','Office address (for map)'],['whatsapp','واتساپ (کد کشور، فقط اعداد)','WhatsApp (country code, digits only)'],['instagram','لینک اینستاگرام (https)','Instagram profile URL (https)'],['linkedin','لینک لینکدین (https)','LinkedIn profile URL (https)'],['telegram','لینک تلگرام (https)','Telegram URL (https)']].map(([key,f,e])=><label key={key}>{fa?f:e}<input name={key} type={key==='email'?'email':'text'} value={draft[key]} required={key.startsWith('brand')} onChange={e=>setDraft({...draft,[key]:e.target.value})} maxLength={300} dir={['brandEn','phone','email','whatsapp'].includes(key)?'ltr':undefined}/></label>)}<button className="button" disabled={busy}>{fa?'ذخیره اطلاعات':'Save details'}<Icon name="Save" size={18}/></button></form></div>}
 </section>;
}
function ShipmentEditor({shipment,busy,save}){const {fa}=useSite();const [data,setData]=useState({origin:shipment.origin,destination:shipment.destination,status:shipment.status});useEffect(()=>setData({origin:shipment.origin,destination:shipment.destination,status:shipment.status}),[shipment]);return <form className="shipment-editor" onSubmit={e=>{e.preventDefault();save(data);}}><b dir="ltr">{shipment.code}</b><label>{fa?'مبدأ':'Origin'}<input value={data.origin} required maxLength={200} onChange={e=>setData({...data,origin:e.target.value})}/></label><label>{fa?'مقصد':'Destination'}<input value={data.destination} required maxLength={200} onChange={e=>setData({...data,destination:e.target.value})}/></label><label>{fa?'وضعیت':'Status'}<select value={data.status} onChange={e=>setData({...data,status:e.target.value})}>{stages.map(s=><option key={s} value={s}>{fa?stageFa[s]:s}</option>)}</select></label><button className="button small" disabled={busy}>{fa?'ذخیره':'Save'}</button></form>;}
